server:
  port: 8090
spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: krainet.notification@gmail.com
    password: rypywrlimazpqcja
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/krainet
    username: krainet_user
    password: secure_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    table: flyway_schema_history_notification
logging:
  level:
    root: INFO
